"""
refresh_details.py — re-fetch every known course's detail page and refresh
points/end_date/course_code/syllabus/learning_outcomes/prerequisites in
data/courses.json, without re-scraping any course lists.

Also writes the same refreshed fields back into whichever raw/*.json points
file(s) already have an entry for that course, so raw/ and data/courses.json
never drift apart for points/end_date/course_code/prerequisites — a later
run of build_courses.py (which scrape_all.py runs automatically) attaches
those straight from raw/*.json, so without this it would silently revert
them to whatever was there before. (syllabus/learning_outcomes are synced
into raw/*.json too, for consistency, but build_courses.py never actually
reads them from there — see its module docstring for why.)

Unlike fetch-points.js (which needs a hand-maintained COURSE_PAIRS array
pasted into a browser console, regenerated by hand whenever the catalog
changes), this reads the pid/pprev pairs directly out of the existing
data/courses.json, so there's nothing to keep in sync — just run it.

Same "real local browser, not a remote scraper" reasoning as scrape_all.py
applies here too.

SETUP (once, same as scrape_all.py):
    raw/my_env/bin/pip install playwright
    raw/my_env/bin/playwright install chromium

USAGE:
    raw/my_env/bin/python3 scripts/refresh_details.py
    raw/my_env/bin/python3 scripts/refresh_details.py --headless
    raw/my_env/bin/python3 scripts/refresh_details.py --delay 0.5   # slower, more polite
"""
import argparse
import json
import sys
import time
from html import unescape
from pathlib import Path

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    print("Playwright isn't installed in this Python environment. Run:")
    print("  raw/my_env/bin/pip install playwright")
    print("  raw/my_env/bin/playwright install chromium")
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))
from parse_courses import parse_course_detail  # noqa: E402
from build_courses import _clean_detail_text  # noqa: E402

COURSES_PATH = REPO_ROOT / "data" / "courses.json"
RAW_DIR = REPO_ROOT / "raw"
DETAIL_BASE = "https://erez.weizmann.ac.il/apx/r/ws1/186/30"
RAW_DETAIL_FIELDS = ("points", "end_date", "course_code", "syllabus", "learning_outcomes", "prerequisites")


def load_raw_points_files(raw_dir):
    """Load every points/end-date *.json file in raw_dir, and index which
    file(s) each "pid-pprev" key appears in, so refreshed data can be written
    back in place — same key format build_courses.py's load_points_map uses."""
    files = {}
    key_locations = {}
    for path in sorted(raw_dir.glob("*.json")):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            continue  # a course-list JSON, not a points/end-date map
        files[path] = data
        for key in data:
            key_locations.setdefault(key, []).append(path)
    return files, key_locations


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--headless", action="store_true", help="Run without a visible browser window")
    parser.add_argument("--delay", type=float, default=0.25, help="Seconds to wait between requests (politeness)")
    args = parser.parse_args()

    with open(COURSES_PATH, "r", encoding="utf-8") as f:
        courses = json.load(f)

    raw_files, raw_key_locations = load_raw_points_files(RAW_DIR)
    print(f"Refreshing detail data for {len(courses)} course(s)...")

    updated = failed = 0
    dirty_files = set()
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=args.headless)
        page = browser.new_page()
        for i, c in enumerate(courses, 1):
            pid, pprev = c.get("course_id"), c.get("group_id")
            if not pid:
                continue
            url = f"{DETAIL_BASE}?pid={pid}&pprev={pprev or 0}"
            try:
                page.goto(url, wait_until="load", timeout=20000)
                detail = parse_course_detail(page.content())
            except Exception as e:
                failed += 1
                print(f"  [{i}/{len(courses)}] {c.get('title', '?')[:40]!r} failed: {e}")
                continue

            c["points"] = detail.get("points")
            end_date = detail.get("end_date")
            c["end_date"] = unescape(end_date) if end_date else None
            course_code = detail.get("course_code")
            if course_code:
                c["course_code"] = unescape(course_code)
            for field in ("syllabus", "learning_outcomes", "prerequisites"):
                val = _clean_detail_text(detail.get(field))
                if val:
                    c[field] = val

            raw_key = f"{pid}-{pprev}"
            for raw_path in raw_key_locations.get(raw_key, ()):
                raw_files[raw_path][raw_key] = {f: detail.get(f) for f in RAW_DETAIL_FIELDS}
                dirty_files.add(raw_path)

            updated += 1
            if i % 50 == 0 or i == len(courses):
                print(f"  [{i}/{len(courses)}] ...")
            time.sleep(args.delay)
        browser.close()

    with open(COURSES_PATH, "w", encoding="utf-8") as f:
        json.dump(courses, f, ensure_ascii=False, indent=2)

    for raw_path in dirty_files:
        with open(raw_path, "w", encoding="utf-8") as f:
            json.dump(raw_files[raw_path], f, ensure_ascii=False, indent=2)

    print(f"\nDone. Refreshed {updated}/{len(courses)} course(s), {failed} failed -> {COURSES_PATH}")
    if dirty_files:
        print(f"Kept {len(dirty_files)} raw/*.json file(s) in sync so a later build_courses.py run won't revert this.")
    with_syllabus = sum(1 for c in courses if c.get("syllabus"))
    with_outcomes = sum(1 for c in courses if c.get("learning_outcomes"))
    with_prereq = sum(1 for c in courses if c.get("prerequisites"))
    print(f"Now: {with_syllabus} with syllabus, {with_outcomes} with learning_outcomes, {with_prereq} with prerequisites.")


if __name__ == "__main__":
    main()
